/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultIndexImport } from './routes/result/index'
import { Route as QuestionsIndexImport } from './routes/questions/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ResultIndexRoute = ResultIndexImport.update({
  path: '/result/',
  getParentRoute: () => rootRoute,
} as any)

const QuestionsIndexRoute = QuestionsIndexImport.update({
  path: '/questions/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/questions/': {
      preLoaderRoute: typeof QuestionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/result/': {
      preLoaderRoute: typeof ResultIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  QuestionsIndexRoute,
  ResultIndexRoute,
])

/* prettier-ignore-end */
